[package]
name = "celeste"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.15"
bevy_rapier2d = "0.28"
bevy_ecs_ldtk = "0.11"
rand = "0.8"